/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export interface ScoreEntry { 'player' : string, 'score' : bigint }
export interface _SERVICE {
  'getLeaderboard' : ActorMethod<[string], Array<ScoreEntry>>,
  'getMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getPersonalBest' : ActorMethod<[string, string], [] | [bigint]>,
  'getRoomMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'sendMessage' : ActorMethod<[string, string], bigint>,
  'sendRoomMessage' : ActorMethod<[string, string, string], bigint>,
  'submitScore' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];