/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'player' : IDL.Text,
  'score' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getPersonalBest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getRoomMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'sendRoomMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({ 'player' : IDL.Text, 'score' : IDL.Nat });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getPersonalBest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getRoomMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'sendRoomMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };